[workspace]
resolver = "3"
members = ["crates/urlz", "crates/urlz-cli", "crates/xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cricsion/urlz"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "2"
num-bigint = "0.4"
num-traits = "0.2"
bitstream-io = "2"
proptest = "1"
criterion = "0.5"
assert_cmd = "2"
predicates = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
strip = "symbols"

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false